language: generic
dist: xenial

install:
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # proselint
  - sudo pip install proselint

script:
  # Check dead links
  - rm .travis.yml
  - travis_wait 60 ./scripts/check_dead_links
  # proselint
  - cd content
  - for filename in `ls *.md`; do proselint $filename; done
  - cd ..
